// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.Ambiente;
import com.itchyno.iteff.domain.AmbienteDataOnDemand;
import com.itchyno.iteff.domain.AmbienteIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AmbienteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AmbienteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AmbienteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AmbienteIntegrationTest: @Transactional;
    
    @Autowired
    AmbienteDataOnDemand AmbienteIntegrationTest.dod;
    
    @Test
    public void AmbienteIntegrationTest.testCountAmbientes() {
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", dod.getRandomAmbiente());
        long count = Ambiente.countAmbientes();
        Assert.assertTrue("Counter for 'Ambiente' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AmbienteIntegrationTest.testFindAmbiente() {
        Ambiente obj = dod.getRandomAmbiente();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to provide an identifier", id);
        obj = Ambiente.findAmbiente(id);
        Assert.assertNotNull("Find method for 'Ambiente' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Ambiente' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AmbienteIntegrationTest.testFindAllAmbientes() {
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", dod.getRandomAmbiente());
        long count = Ambiente.countAmbientes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Ambiente', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Ambiente> result = Ambiente.findAllAmbientes();
        Assert.assertNotNull("Find all method for 'Ambiente' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Ambiente' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AmbienteIntegrationTest.testFindAmbienteEntries() {
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", dod.getRandomAmbiente());
        long count = Ambiente.countAmbientes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Ambiente> result = Ambiente.findAmbienteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Ambiente' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Ambiente' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AmbienteIntegrationTest.testFlush() {
        Ambiente obj = dod.getRandomAmbiente();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to provide an identifier", id);
        obj = Ambiente.findAmbiente(id);
        Assert.assertNotNull("Find method for 'Ambiente' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAmbiente(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Ambiente' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AmbienteIntegrationTest.testMergeUpdate() {
        Ambiente obj = dod.getRandomAmbiente();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to provide an identifier", id);
        obj = Ambiente.findAmbiente(id);
        boolean modified =  dod.modifyAmbiente(obj);
        Integer currentVersion = obj.getVersion();
        Ambiente merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Ambiente' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AmbienteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", dod.getRandomAmbiente());
        Ambiente obj = dod.getNewTransientAmbiente(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Ambiente' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Ambiente' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AmbienteIntegrationTest.testRemove() {
        Ambiente obj = dod.getRandomAmbiente();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ambiente' failed to provide an identifier", id);
        obj = Ambiente.findAmbiente(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Ambiente' with identifier '" + id + "'", Ambiente.findAmbiente(id));
    }
    
}
