// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.Movimentacao;
import com.itchyno.iteff.domain.MovimentacaoDataOnDemand;
import com.itchyno.iteff.domain.MovimentacaoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MovimentacaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MovimentacaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MovimentacaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MovimentacaoIntegrationTest: @Transactional;
    
    @Autowired
    MovimentacaoDataOnDemand MovimentacaoIntegrationTest.dod;
    
    @Test
    public void MovimentacaoIntegrationTest.testCountMovimentacaos() {
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", dod.getRandomMovimentacao());
        long count = Movimentacao.countMovimentacaos();
        Assert.assertTrue("Counter for 'Movimentacao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MovimentacaoIntegrationTest.testFindMovimentacao() {
        Movimentacao obj = dod.getRandomMovimentacao();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to provide an identifier", id);
        obj = Movimentacao.findMovimentacao(id);
        Assert.assertNotNull("Find method for 'Movimentacao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Movimentacao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MovimentacaoIntegrationTest.testFindAllMovimentacaos() {
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", dod.getRandomMovimentacao());
        long count = Movimentacao.countMovimentacaos();
        Assert.assertTrue("Too expensive to perform a find all test for 'Movimentacao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Movimentacao> result = Movimentacao.findAllMovimentacaos();
        Assert.assertNotNull("Find all method for 'Movimentacao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Movimentacao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MovimentacaoIntegrationTest.testFindMovimentacaoEntries() {
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", dod.getRandomMovimentacao());
        long count = Movimentacao.countMovimentacaos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Movimentacao> result = Movimentacao.findMovimentacaoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Movimentacao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Movimentacao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MovimentacaoIntegrationTest.testFlush() {
        Movimentacao obj = dod.getRandomMovimentacao();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to provide an identifier", id);
        obj = Movimentacao.findMovimentacao(id);
        Assert.assertNotNull("Find method for 'Movimentacao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMovimentacao(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Movimentacao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MovimentacaoIntegrationTest.testMergeUpdate() {
        Movimentacao obj = dod.getRandomMovimentacao();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to provide an identifier", id);
        obj = Movimentacao.findMovimentacao(id);
        boolean modified =  dod.modifyMovimentacao(obj);
        Integer currentVersion = obj.getVersion();
        Movimentacao merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Movimentacao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MovimentacaoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", dod.getRandomMovimentacao());
        Movimentacao obj = dod.getNewTransientMovimentacao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Movimentacao' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Movimentacao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MovimentacaoIntegrationTest.testRemove() {
        Movimentacao obj = dod.getRandomMovimentacao();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimentacao' failed to provide an identifier", id);
        obj = Movimentacao.findMovimentacao(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Movimentacao' with identifier '" + id + "'", Movimentacao.findMovimentacao(id));
    }
    
}
