// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.Produto;
import com.itchyno.iteff.domain.ProdutoDataOnDemand;
import com.itchyno.iteff.domain.ProdutoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProdutoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProdutoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProdutoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProdutoIntegrationTest: @Transactional;
    
    @Autowired
    ProdutoDataOnDemand ProdutoIntegrationTest.dod;
    
    @Test
    public void ProdutoIntegrationTest.testCountProdutoes() {
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        long count = Produto.countProdutoes();
        Assert.assertTrue("Counter for 'Produto' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProdutoIntegrationTest.testFindProduto() {
        Produto obj = dod.getRandomProduto();
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = Produto.findProduto(id);
        Assert.assertNotNull("Find method for 'Produto' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Produto' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProdutoIntegrationTest.testFindAllProdutoes() {
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        long count = Produto.countProdutoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Produto', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Produto> result = Produto.findAllProdutoes();
        Assert.assertNotNull("Find all method for 'Produto' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Produto' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProdutoIntegrationTest.testFindProdutoEntries() {
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        long count = Produto.countProdutoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Produto> result = Produto.findProdutoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Produto' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Produto' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProdutoIntegrationTest.testFlush() {
        Produto obj = dod.getRandomProduto();
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = Produto.findProduto(id);
        Assert.assertNotNull("Find method for 'Produto' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProduto(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Produto' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProdutoIntegrationTest.testMergeUpdate() {
        Produto obj = dod.getRandomProduto();
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = Produto.findProduto(id);
        boolean modified =  dod.modifyProduto(obj);
        Integer currentVersion = obj.getVersion();
        Produto merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Produto' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProdutoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        Produto obj = dod.getNewTransientProduto(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Produto' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Produto' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Produto' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProdutoIntegrationTest.testRemove() {
        Produto obj = dod.getRandomProduto();
        Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = Produto.findProduto(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Produto' with identifier '" + id + "'", Produto.findProduto(id));
    }
    
}
