// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.TipoMovimentacao;
import com.itchyno.iteff.domain.TipoMovimentacaoDataOnDemand;
import com.itchyno.iteff.domain.TipoMovimentacaoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipoMovimentacaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TipoMovimentacaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TipoMovimentacaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TipoMovimentacaoIntegrationTest: @Transactional;
    
    @Autowired
    TipoMovimentacaoDataOnDemand TipoMovimentacaoIntegrationTest.dod;
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testCountTipoMovimentacaos() {
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", dod.getRandomTipoMovimentacao());
        long count = TipoMovimentacao.countTipoMovimentacaos();
        Assert.assertTrue("Counter for 'TipoMovimentacao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testFindTipoMovimentacao() {
        TipoMovimentacao obj = dod.getRandomTipoMovimentacao();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to provide an identifier", id);
        obj = TipoMovimentacao.findTipoMovimentacao(id);
        Assert.assertNotNull("Find method for 'TipoMovimentacao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TipoMovimentacao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testFindAllTipoMovimentacaos() {
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", dod.getRandomTipoMovimentacao());
        long count = TipoMovimentacao.countTipoMovimentacaos();
        Assert.assertTrue("Too expensive to perform a find all test for 'TipoMovimentacao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TipoMovimentacao> result = TipoMovimentacao.findAllTipoMovimentacaos();
        Assert.assertNotNull("Find all method for 'TipoMovimentacao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TipoMovimentacao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testFindTipoMovimentacaoEntries() {
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", dod.getRandomTipoMovimentacao());
        long count = TipoMovimentacao.countTipoMovimentacaos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TipoMovimentacao> result = TipoMovimentacao.findTipoMovimentacaoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TipoMovimentacao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TipoMovimentacao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testFlush() {
        TipoMovimentacao obj = dod.getRandomTipoMovimentacao();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to provide an identifier", id);
        obj = TipoMovimentacao.findTipoMovimentacao(id);
        Assert.assertNotNull("Find method for 'TipoMovimentacao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTipoMovimentacao(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TipoMovimentacao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testMergeUpdate() {
        TipoMovimentacao obj = dod.getRandomTipoMovimentacao();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to provide an identifier", id);
        obj = TipoMovimentacao.findTipoMovimentacao(id);
        boolean modified =  dod.modifyTipoMovimentacao(obj);
        Integer currentVersion = obj.getVersion();
        TipoMovimentacao merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TipoMovimentacao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", dod.getRandomTipoMovimentacao());
        TipoMovimentacao obj = dod.getNewTransientTipoMovimentacao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TipoMovimentacao' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TipoMovimentacao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TipoMovimentacaoIntegrationTest.testRemove() {
        TipoMovimentacao obj = dod.getRandomTipoMovimentacao();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoMovimentacao' failed to provide an identifier", id);
        obj = TipoMovimentacao.findTipoMovimentacao(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TipoMovimentacao' with identifier '" + id + "'", TipoMovimentacao.findTipoMovimentacao(id));
    }
    
}
