// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.TipoEquipamento;
import com.itchyno.iteff.domain.TipoEquipamentoDataOnDemand;
import com.itchyno.iteff.domain.TipoEquipamentoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipoEquipamentoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TipoEquipamentoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TipoEquipamentoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TipoEquipamentoIntegrationTest: @Transactional;
    
    @Autowired
    TipoEquipamentoDataOnDemand TipoEquipamentoIntegrationTest.dod;
    
    @Test
    public void TipoEquipamentoIntegrationTest.testCountTipoEquipamentoes() {
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", dod.getRandomTipoEquipamento());
        long count = TipoEquipamento.countTipoEquipamentoes();
        Assert.assertTrue("Counter for 'TipoEquipamento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TipoEquipamentoIntegrationTest.testFindTipoEquipamento() {
        TipoEquipamento obj = dod.getRandomTipoEquipamento();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to provide an identifier", id);
        obj = TipoEquipamento.findTipoEquipamento(id);
        Assert.assertNotNull("Find method for 'TipoEquipamento' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TipoEquipamento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TipoEquipamentoIntegrationTest.testFindAllTipoEquipamentoes() {
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", dod.getRandomTipoEquipamento());
        long count = TipoEquipamento.countTipoEquipamentoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'TipoEquipamento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TipoEquipamento> result = TipoEquipamento.findAllTipoEquipamentoes();
        Assert.assertNotNull("Find all method for 'TipoEquipamento' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TipoEquipamento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TipoEquipamentoIntegrationTest.testFindTipoEquipamentoEntries() {
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", dod.getRandomTipoEquipamento());
        long count = TipoEquipamento.countTipoEquipamentoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TipoEquipamento> result = TipoEquipamento.findTipoEquipamentoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TipoEquipamento' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TipoEquipamento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TipoEquipamentoIntegrationTest.testFlush() {
        TipoEquipamento obj = dod.getRandomTipoEquipamento();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to provide an identifier", id);
        obj = TipoEquipamento.findTipoEquipamento(id);
        Assert.assertNotNull("Find method for 'TipoEquipamento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTipoEquipamento(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TipoEquipamento' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoEquipamentoIntegrationTest.testMergeUpdate() {
        TipoEquipamento obj = dod.getRandomTipoEquipamento();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to provide an identifier", id);
        obj = TipoEquipamento.findTipoEquipamento(id);
        boolean modified =  dod.modifyTipoEquipamento(obj);
        Integer currentVersion = obj.getVersion();
        TipoEquipamento merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TipoEquipamento' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoEquipamentoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", dod.getRandomTipoEquipamento());
        TipoEquipamento obj = dod.getNewTransientTipoEquipamento(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TipoEquipamento' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TipoEquipamento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TipoEquipamentoIntegrationTest.testRemove() {
        TipoEquipamento obj = dod.getRandomTipoEquipamento();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEquipamento' failed to provide an identifier", id);
        obj = TipoEquipamento.findTipoEquipamento(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TipoEquipamento' with identifier '" + id + "'", TipoEquipamento.findTipoEquipamento(id));
    }
    
}
