// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.Ambiente;
import com.itchyno.iteff.domain.AmbienteDataOnDemand;
import com.itchyno.iteff.domain.TipoMovimentacao;
import com.itchyno.iteff.domain.TipoMovimentacaoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TipoMovimentacaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TipoMovimentacaoDataOnDemand: @Component;
    
    private Random TipoMovimentacaoDataOnDemand.rnd = new SecureRandom();
    
    private List<TipoMovimentacao> TipoMovimentacaoDataOnDemand.data;
    
    @Autowired
    AmbienteDataOnDemand TipoMovimentacaoDataOnDemand.ambienteDataOnDemand;
    
    public TipoMovimentacao TipoMovimentacaoDataOnDemand.getNewTransientTipoMovimentacao(int index) {
        TipoMovimentacao obj = new TipoMovimentacao();
        setCategoria(obj, index);
        setCodigo(obj, index);
        setNome(obj, index);
        return obj;
    }
    
    public void TipoMovimentacaoDataOnDemand.setCategoria(TipoMovimentacao obj, int index) {
        String categoria = "categoria_" + index;
        if (categoria.length() > 255) {
            categoria = categoria.substring(0, 255);
        }
        obj.setCategoria(categoria);
    }
    
    public void TipoMovimentacaoDataOnDemand.setCodigo(TipoMovimentacao obj, int index) {
        Ambiente codigo = ambienteDataOnDemand.getRandomAmbiente();
        obj.setCodigo(codigo);
    }
    
    public void TipoMovimentacaoDataOnDemand.setNome(TipoMovimentacao obj, int index) {
        String nome = "nome_" + index;
        if (nome.length() > 255) {
            nome = nome.substring(0, 255);
        }
        obj.setNome(nome);
    }
    
    public TipoMovimentacao TipoMovimentacaoDataOnDemand.getSpecificTipoMovimentacao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TipoMovimentacao obj = data.get(index);
        Long id = obj.getId();
        return TipoMovimentacao.findTipoMovimentacao(id);
    }
    
    public TipoMovimentacao TipoMovimentacaoDataOnDemand.getRandomTipoMovimentacao() {
        init();
        TipoMovimentacao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TipoMovimentacao.findTipoMovimentacao(id);
    }
    
    public boolean TipoMovimentacaoDataOnDemand.modifyTipoMovimentacao(TipoMovimentacao obj) {
        return false;
    }
    
    public void TipoMovimentacaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TipoMovimentacao.findTipoMovimentacaoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TipoMovimentacao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TipoMovimentacao>();
        for (int i = 0; i < 10; i++) {
            TipoMovimentacao obj = getNewTransientTipoMovimentacao(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
