// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.Ambiente;
import com.itchyno.iteff.domain.AmbienteDataOnDemand;
import com.itchyno.iteff.domain.TipoProduto;
import com.itchyno.iteff.domain.TipoProdutoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TipoProdutoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TipoProdutoDataOnDemand: @Component;
    
    private Random TipoProdutoDataOnDemand.rnd = new SecureRandom();
    
    private List<TipoProduto> TipoProdutoDataOnDemand.data;
    
    @Autowired
    AmbienteDataOnDemand TipoProdutoDataOnDemand.ambienteDataOnDemand;
    
    public TipoProduto TipoProdutoDataOnDemand.getNewTransientTipoProduto(int index) {
        TipoProduto obj = new TipoProduto();
        setCategoria(obj, index);
        setCodigo(obj, index);
        setNome(obj, index);
        return obj;
    }
    
    public void TipoProdutoDataOnDemand.setCategoria(TipoProduto obj, int index) {
        String categoria = "categoria_" + index;
        if (categoria.length() > 255) {
            categoria = categoria.substring(0, 255);
        }
        obj.setCategoria(categoria);
    }
    
    public void TipoProdutoDataOnDemand.setCodigo(TipoProduto obj, int index) {
        Ambiente codigo = ambienteDataOnDemand.getRandomAmbiente();
        obj.setCodigo(codigo);
    }
    
    public void TipoProdutoDataOnDemand.setNome(TipoProduto obj, int index) {
        String nome = "nome_" + index;
        if (nome.length() > 255) {
            nome = nome.substring(0, 255);
        }
        obj.setNome(nome);
    }
    
    public TipoProduto TipoProdutoDataOnDemand.getSpecificTipoProduto(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TipoProduto obj = data.get(index);
        Long id = obj.getId();
        return TipoProduto.findTipoProduto(id);
    }
    
    public TipoProduto TipoProdutoDataOnDemand.getRandomTipoProduto() {
        init();
        TipoProduto obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TipoProduto.findTipoProduto(id);
    }
    
    public boolean TipoProdutoDataOnDemand.modifyTipoProduto(TipoProduto obj) {
        return false;
    }
    
    public void TipoProdutoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TipoProduto.findTipoProdutoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TipoProduto' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TipoProduto>();
        for (int i = 0; i < 10; i++) {
            TipoProduto obj = getNewTransientTipoProduto(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
