// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itchyno.iteff.domain;

import com.itchyno.iteff.domain.TipoProduto;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoProduto_Roo_Configurable {
    
    declare @type: TipoProduto: @Configurable;
    
}
